# tên của workflow là Docker Image CI
name: Docker Image CI

# điều kiện trigger
on:
  # đẩy code lên branch main
  push:
    branches: [ "main" ]
  # pull request lên branch main
  pull_request:
    branches: [ "main" ]

# mô tả công việc
jobs:
  # công việc đầu tiên là build
  build:
    # chạy trên máy ảo ubuntu của github
    runs-on: ubuntu-latest
    # các bước thực hiện
    steps:
    # 2. Setup Node.js (để chạy npm run test)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Cài dependency
    - name: Install dependencies
      run: npm ci

    # 4. Chạy test
    - name: Run tests
      run: npm run test

    # checkout code từ repo, clone code về máy
    - uses: actions/checkout@v4
    # build image docker
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
